name: "➕ Repository Request"
description: "Request a new repository"

title: "New repository request"

labels:
  - "repo-request"
  - "issue-ops"

assignees:
  - "gesiud"

projects: "gesiud/testowy projekt"

body:
  - type: input
    id: name
    attributes:
      label: "Nazwa"
      description: "Name of the repository in lower-case and kebab casing"
      placeholder: "your-name-kebab"
    validations:
      required: true

  - type: dropdown
    id: departament
    attributes:
      label: "Departament"
      description: "Select departament"
      multiple: false
      options:
        - dep 1
        - dep 2
    validations:
      required: true
